extends CanvasLayer

var pages = []
var current_page_id = 0
var b_active = false
var title = ""

func _ready():
	$Panel.visible = false	
	
func start(book):
	if b_active:
		return
	b_active = true
	$Panel.visible = true
	pages = load_dialogue(book)
	current_page_id = -1
	next_page()

func load_dialogue(book):	
	title = book
	var b1p1 = "What is Criptografic Failures? \n\n" \
			 + "Certain types of data, including access credentials,  \n" \
			 + "banking information, and confidential company data, \n" \
			 + "among others, must be subjected to encryption. \n\n" \
			 + "This is not only a legal requirement but also crucial \n" \
			 + "but also crucial for preventing potential \n" \
			 + "catastrophic consequences to the company in the \n" \
			 + "event that unauthorized individuals, particularly \n" \
			 + "cybercriminals, gain unauthorized access to them. \n\n" \
			 + "In essence, to ensure that such data is exclusively \n" \
			 + "accessible to authorized personnel within the \n" \
			 + "organization, it is imperative to implement encryption \n" \
			 + "mechanisms employing standardized and resilient \n" \
			 + "algorithms and protocols."
			
	var b1p2 = "What is the Impact of Cryptographic Failure? \n\n"\
			 + "Insufficient security measures expose vulnerabilities \n"\
			 + "manipulate that enable attackers to illicitly acquire   \n"\
			 + "and data, leading to fraudulent activities, identity \n"\
			 + "theft, and potentially severe consequences. \n\n" \
			 + "Malicious actors employ various techniques such as \n"\
			 + "attempting to pilfer encryption keys, executing \n"\
			 + "man-in-the-middle attacks, or extracting data from \n"\
			 + "servers, during transit, or from web browsers. \n"\
			 + "These actions invariably compromise the integrity  \n"\
			 + "of ensitive information.\n\n"\
			 + "But the repercussions of a cryptographic failure \n"\
			 + "extend beyond the mere extraction of individual \n"\
			 + "user data."
			
	var b1p3 = "Attackers can gain unauthorized access to complete \n"\
			+ "databases containing thousands of pieces of \n"\
			+ "sensitive information, resulting in substantial data \n"\
			+ "theft, public exposure, breaches, and other critical \n"\
			+ "issues that directly impact business operations.  \n\n"\
			+ "One can also envision a scenario where an attacker \n"\
			+ "obtains the credentials of an administrator, \n"\
			+ "subsequently attaining complete control over a \n"\
			+ "server.\n\n"\
			+ "Cryptographic failures can inflict irreparable \n"\
			+ "damage to reputation and expose organizations to \n"\
			+ "substantial legal ramifications."
				
	var b2p1 = "Scenario #1: \n" \
			+ "An application encrypts credit card number in a \n" \
			+ "database using automatic database encryption. \n"\
			+ "However, this data is automatically decrypted \n"\
			+ "when retrieved, allowing a SQL injection flaw \n"\
			+ "to retrieve credit card numbers in clear text.\n\n"\
			+ "Scenario #2:\n" \
			+ "The password database uses unsalted or simple \n"\
			+ "hashes to store everyone's passwords. A file \n"\
			+ "upload flaw allows an attacker to retrieve the \n"\
			+ "password database. All the unsalted hashes can be \n"\
			+ "exposed with a rainbow table of pre-calculated \n"\
			+ "hashes. Hashes generated by simple or fast hash \n"\
			+ "functions may be cracked by GPUs, even if they \n"\
			+ "were salted.\n"\
			
	var b2p2 = "Scenario #3: \n" \
			+ "A site doesn't use or enforce TLS\n"\
			+ "for all pages or supports weak encryption. An \n"\
			+ "attacker monitors network traffic (e.g., at an \n"\
			+ "insecure wireless network), downgrades \n"\
			+ "connections from HTTPS to HTTP, intercepts \n"\
			+ "requests, and steals the user's session cookie.\n"\
			+ "The attacker then replays this cookie and \n"\
			+ "hijacks the user's (authenticated) session, \n"\
			+ "accessing or modifying the user's private data. \n"\
			+ "Instead of the above they could alter all \n"\
			+ "transported data, e.g., the recipient of a money \n"\
			+ "transfer.\n"
			
	var b3p1 = "How to prevent CFs:\n\n" \
				+ "1. Categorize the data processed, stored, or \n"\
				+ "transmitted by an application. Identify sensitive \n"\
				+ "data based on privacy laws, regulatory requirements,\n"\
				+ "or business needs.\n"\
				+ "2. Minimize unnecessary storage of sensitive data. \n"\
				+ "Dispose of it promptly or utilize PCI DSS compliant \n"\
				+ "tokenization or truncation methods. \n"\
				+ "3. Ensure that all sensitive data at rest is encrypted.\n"\
				+ "4. Implement up-to-date and robust standard ,\n"\
				+ "algorithms protocols, and keys, and employ proper  \n"\
				+ "key management practices.\n"\
				+ "5. Encrypt all data in transit using secure protocols \n"\
				+ "such as TLS with forward secrecy (FS) ciphers. \n"\
				+ "Prioritize ciphers at the server level and set secure\n"\
				+ "parameters. Enforce encryption through directives \n"\
				
	var b3p2 = "like HTTP Strict Transport Security (HSTS).\n"\
				+ "6. Disable caching for responses containing sensitive \n"\
				+ "data.\n"\
				+ "7. Apply necessary security controls based on the  \n"\
				+ "data classification.\n"\
				+ "	8. Avoid using outdated protocols like FTP and SMTP \n"\
				+ "	for transmitting sensitive data.\n"\
				+ "	9. Store passwords using strong adaptive and salted \n"\
				+ "	hashing functions with a work factor (delay factor), \n"\
				+ "	such as Argon2, scrypt, bcrypt, or PBKDF2.\n"\
				+ "	10. Choose appropriate initialization vectors for the \n"\
				+ "	mode of operation. For many modes, use a \n"\
				+ "	cryptographically secure pseudo-random number \n"\
				+ "	generator (CSPRNG). If a mode requires a nonce, the \n"\
				+ "	initialization vector (IV) does not need a CSPRNG. \n"\
				+ "	In all cases, avoid reusing the IV with a fixed key.\n"
				
	var b3p3 = 	"11. Prefer authenticated encryption over basic \n"\
				+ "encryption.\n"\
				+ "12. Generate keys randomly using cryptographic  \n"\
				+ "methods and store them as byte arrays in memory. \n"\
				+ "If a password is used, convert it to a key using an  \n"\
				+ "appropriate password-based key derivation function.\n"\
				+ "13. Ensure the use of cryptographic randomness  \n"\
				+ "where necessary and avoid predictable seeding or \n"\
				+ "low entropy. Most modern APIs do not require  \n"\
				+ "developers to seed the CSPRNG for security .\n"\
				+ "purposes\n"\
				+ "14. Steer clear of deprecated cryptographic functions \n"\
				+ "and padding schemes such as MD5, SHA1, and   \n"\
				+ "PKCS number 1 v1.5.\n"\
				+ "15. Independently verify the effectiveness of \n"\
				+ "configurations and settings."
	
	if book == "CF-1 Intro":
		return [b1p1,b1p2,b1p3]
	if book == "CF-2 Attack":
		return [b2p1,b2p2]
	if book == "CF-3 Defense":
		return [b3p1,b3p2,b3p3]
	

func _input(event):
	if not b_active:
		return
	if event.is_action_pressed("ui_accept"):
		next_page()
		
func next_page():
	current_page_id += 1
	
	if pages == null or current_page_id >= pages.size():
		$Panel.visible=false
		$Timer.start()
		return	
	$Panel/Title.text = title
	$Panel/Text.text = pages[current_page_id]

func _on_Timer_timeout():
	b_active = false
